IntelLabs/vdms

src/PMGDQueryHandler.cc
Tested this by creating an exception through pmgd_queries.cc and it doesn't hang. Luis, could you please try out with your test case?
=> Fix lock position bug in PMGDQueryHandler

src/DescriptorsCommand.cc, src/DescriptorsCommand.h, src/PMGDQuery.h, src/QueryHandler.cc, tests/python/TestEntities.py, tests/python/TestRetail.py, tests/python/longquery.py
=> Fix bug descriptors pmgdqh

config-vdms.json, run_server.sh, src/DescriptorsCommand.cc, src/DescriptorsCommand.h, src/ImageCommand.cc, src/ImageCommand.h, src/PMGDQueryHandler.cc, src/RSCommand.cc, src/RSCommand.h, src/VDMSConfig.cc, src/VDMSConfig.h, tests/config-add10-tests.json, tests/config-addfind-tests.json, tests/config-tests.json, tests/config-update-tests.json, tests/python/clean.sh, tests/python/config-tests.json, tests/python/run_python_tests.sh
=> Fix directories handling

src/PMGDQueryHandler.cc, src/VDMSConfig.h
Including parameter to control the number of allocators in PMGD at creation time.
Also created a ConfigFile wiki page: https://github.com/IntelLabs/vdms/wiki/ConfigFile
=> Add PMGD num_allocators to config file

tests/python/TestDescriptors.py, tests/python/TestFindDescriptors.py, utils/src/api_schema/api_schema.json
Expose the metric param for creation of Descriptor Sets
=> Add descriptors metric

src/ImageCommand.cc, tests/python/TestImages.py
=> Fix fimg noblob (#90)

src/DescriptorsCommand.cc, src/DescriptorsCommand.h, tests/python/TestFindDescriptors.py, utils/src/api_schema/api_schema.json
=> Fix find desc (#43, #91)

docker/base/Dockerfile
All tests passing, new docker images updated at hub.docker.com/intellabs
=> Remove VCL from Base Docker

tests/python/TestEngineDescriptors.py
=> Add/Reorg Descriptors Tests

include/vcl/Image.h, src/vcl/Image.cc, src/vcl/ImageData.cc, src/vcl/ImageData.h, src/vcl/VideoData.cc
Optimized video and image code, avoiding copies of cvmats. This increase performance of video read and several image operations by up to 25%.
=> Remove copies in image and video implementation

src/ImageCommand.cc
TDB format only performs better with very large images, and it is usually not the first choice for users, forcing them to explicitly change for format for every insertion or getting error messages. It is better to just go with JPG as the default until we start seeing more use cases showing the benefits of the format.
=> Change default Image format

tests/SConscript
Build script of the unit-test still includes ImageData as dependency.
This causes linking process for unit-tests to fail.
ImageData class has been removed in a previous patch, so it is no longer
needed. This patch removes the dependency.
Signed-off-by: mahircg <mahircan.guel@intel.com>
=> Remove ImageData from unit-test build script

src/ImageCommand.cc, src/ImageCommand.h, src/QueryHandler.cc, src/VideoCommand.cc, src/VideoCommand.h, tests/python/TestVideos.py, utils/src/api_schema/api_schema.json
This patch introduces 'FindFrames' command, that searches for the given
video name and returns a list of frames from the video if it is found.
Currently, FindFrame command relies on OpenCV's frame iteration
capabilities. Thus, the entire video is loaded into memory to be
decoded. In future, the video loading and decoding should be done only
on the requested frame interval.
Signed-off-by: mahircg <mahircan.guel@intel.com>
=> Add FindFrames command

src/PMGDQueryHandler.cc, src/QueryHandler.cc
Already reviewed, just spliting the changes in different PRs.
=> Fix response messages

include/vcl/Video.h, src/vcl/Video.cc, tests/unit_tests/Video_test.cc
Currently, in some of the constructors of Video class, a 'read' operation is
enqueued into the operation queue to ensure that the video is read before
any other operation is performed. This, however, forces a read operation on
on a video object even if there are no operations to apply (i.e.
_operations is empty).
This patch defers read operations until they are absolutely necessary.
This is done by storing the operations in a linked list (rather than a
vector), and adding a read operation to the head of the queue before
perform_operations() invokes each operation in the queue.
Signed-off-by: mahircg <mahircan.guel@intel.com>
=> Do not push 'read' operation on Video constructor

docker/base/Dockerfile
Updates the protobuf version to 3.9.0.
There is a bug on protobuf version 3.6.1 that will cause a segfault in VDMS sometimes. The bug was fixed in later versions. 3.9.0 has been working without problems in multiple systems
=> Update Protobuf version on docker files

SConstruct, src/vcl/Video.cc, tests/SConscript, tests/unit_tests/Video_test.cc
There is currently an incompatibility issue because of video encoding/decoding libraries on the develop branch. Some interfaces are not available on default Ubuntu 16 libraries.
This patch adds a flag that has to be specifically used in order to compile keyframe extraction.
=> Add flag to optionally extract key-frame information on videos

SConstruct
This patch is to prevent an error when compiling and installing the client library only (through the --no-server flag)
=> Add conditionally install of vdms binary

src/VideoCommand.cc, src/VideoCommand.h, tests/python/TestVideos.py, utils/src/api_schema/api_schema.json
This patch introduces 'from_local_file' parameter to AddVideo command,
that allows object creation from local video files in server instead of
blobs transferred from the client.
Signed-off-by: mahircg <mahircan.guel@intel.com>
=> Allow object creation from local files in server

client/python/vdms/vdms.py
=> Remove TCP_QUICKACK when using Python client for Mac

src/DescriptorsCommand.cc, src/DescriptorsCommand.h, src/QueryHandlerPMGD.cc, tests/python/TestDescriptors.py, utils/src/api_schema/api_schema.json
Initial development done, still some refinement and test updates to be done, but ready for initial review.
=> 175 descriptor set optimizations batch inserts
